---
sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.5
  - 2.6

script:
  - bundle exec rake
  - bundle exec rubocop
  # Smoke tests.
  - bundle exec cob_web_index
  - bundle exec cob_web_index ingest --help
